# Generated by Django 4.2.5 on 2023-10-30 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('national_id_hash', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(choices=[(1, 'IN_REVIEW'), (2, 'ACCEPTED'), (3, 'REJECTED'), (4, 'UNKNOWN')], db_index=True, max_length=100)),
                ('check_date', models.DateTimeField(db_index=True)),
                ('access_token', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
