# Generated by Django 4.2.5 on 2023-11-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundcheck',
            name='check_date',
            field=models.DateField(db_index=True),
        ),
    ]
