# Generated by Django 4.2.5 on 2023-10-10 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=128)),
                ('refresh_token', models.CharField(max_length=256)),
                ('expires', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[(1, 'ADDON_USER_APPROVED'), (2, 'USER_PHONE')], max_length=100)),
                ('resource_id', models.CharField(max_length=100, null=True)),
                ('oauth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', related_query_name='scope', to='oauth.oauth')),
            ],
        ),
    ]
