# Generated by Django 4.2.5 on 2023-11-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='permission_type',
            field=models.CharField(choices=[(1, 'ADDON_USER_APPROVED'), (2, 'USER_PHONE'), (3, 'ADDON_STICKY_CREATE')], max_length=100),
        ),
    ]
